name: Update Profile
description: Update your user profile (Avatar).
title: "[Data]: Update Profile"
labels: ["data-submission"]
body:
  - type: dropdown
    id: action_type
    attributes:
      label: Action Type
      options:
        - update_profile
    validations:
      required: true
      
  - type: textarea
    id: payload
    attributes:
      label: JSON Payload
      description: |
        {"avatar": "url", "name": "New Name"}
    validations:
      required: true
